### ISSUE TITLE
Incluir los requerimientos en el readme

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/Votaciones_Premios_Back-end#1]
Incluir requerimientos del readme 

Agregar los pasos de la instalación del proyecto

**Comment by ShannonEchegaray** [comment]
Agregame al Issue

**Comment by JRIVERADDIAZ** [comment]
propongo: 
arquitectura REST 
paradigma OOP

para una mejor escalabilidad

**Comment by GeraAlcantara** [comment]
Se cierra este issue con la PR #6
