### ISSUE TITLE
Asignar rutas en el app

### ISSUE THREAD

**Issue by ShannonEchegaray** [GeraAlcantara/Votaciones_Premios_Back-end#32]
Hay que implementar que las rutas se definan a la hora de asignar el router al app, en vez de hacerlo en la definicion del router.
Al definir las rutas a partir del router se da la posibilidad de, a partir de un typo, no tener las rutas iguales.

Posible error
```js
app.use(userRouter);

// Diciernen las rutas
userRouter.router("/user", ...);
userRouter.router("/users/:id", ...);
```

```js
app.use("/user", userRouter);

// no se puede dicernir ya que se definen en la implementacion del router
userRouter.router("/", ...);
userRouter.router("/:id", ...);
```

**Comment by michaelcardoza** [comment]
@ShannonEchegaray asígnamelo
