### ISSUE TITLE
Agregar @hapi/boom para manejo de errores ordenados

### ISSUE THREAD

**Issue by MarcialFantini** [GeraAlcantara/Votaciones_Premios_Back-end#39]
**[@hapi/boom](https://www.npmjs.com/package/@hapi/boom)** es una biblioteca JavaScript esencial para gestionar errores HTTP de forma estructurada en aplicaciones Node.js. Facilita la creación y personalización de respuestas de errores, lo que permite establecer un estándar para el manejo de errores en la aplicación.

Ejemplo de uso:

javascriptCopy code

`if (!recursoExistente) {
  // Si el recurso no existe, devuelve un error 404 (Not Found)
  const notFoundError = Boom.notFound('El recurso no se ha encontrado');
  throw notFoundError;
}` 

La salida de este ejemplo sería:

jsonCopy code

`{
  "statusCode": 404,
  "error": "Not Found",
  "message": "El recurso no se ha encontrado"
}` 

Las ventajas de utilizar **[@hapi/boom](https://www.npmjs.com/package/@hapi/boom)** son numerosas, ya que ahorra tiempo al definir y manejar diferentes tipos de errores de manera coherente. Otro ejemplo de uso sería:

javascriptCopy code

`Boom.notFound('missing');` 

Lo que generaría esta respuesta:

`{
  "statusCode": 404,
  "error": "Not Found",
  "message": "missing"
}`

**Comment by ShannonEchegaray** [comment]
Buenas @MarcialFantini.

Estuve viendo la libreria, y al parecer tiene la misma utilidad de http-errors.
Comentame que utilidad podriamos integrar en la cual boom podria ser una ventaja.

**Comment by MarcialFantini** [comment]
#### Creación de Errores con `Boom`

`Boom` permite crear errores de manera similar a `http-errors`.

javascriptCopy code

`new Boom.Boom(message, [options])` 

La diferencia principal es que con `Boom`, ya tienes los errores más comunes predefinidos, lo que facilita su uso. Por ejemplo:

-   `Boom.badRequest('invalid query');`
-   `Boom.unauthorized([message], [scheme], [attributes]);`
-   `Boom.paymentRequired([message], [data]);`
-   `Boom.badData('your data is bad and you should feel bad');`
-   `Boom.unauthorized([message], [scheme], [attributes]);`

Estos son solo algunos ejemplos de los errores predefinidos disponibles en `Boom`, lo que simplifica significativamente la creación y manejo de errores en tu aplicación.

**Comment by ShannonEchegaray** [comment]
Buenas @MarcialFantini.

Lo que comentas es exactamente la misma funcionalidad que tiene createHttpError.
Lamentablemente ya habiendola implementado no veo necesario el hecho de cambiar la libreria que tenga la misma utilidad.

Dare por cerrada la issue.
